### ISSUE TITLE
Access denied

### ISSUE THREAD

**Issue by FireflySE** [larry-athey/rpi-smart-still#1]
Hi

I completed the installation successfully but getting this message in browser. 
I guess its a permission issue but where do I start?

Warning: mysqli_connect(): (HY000/1698): Access denied for user 'rssdbuser'@'localhost' in /var/www/html/index.php on line 84

Warning: mysqli_query() expects parameter 1 to be mysqli, bool given in /var/www/html/index.php on line 85

Warning: mysqli_num_rows() expects parameter 1 to be mysqli_result, null given in /var/www/html/index.php on line 86

System settings record is missing, reinstall system from GitHub clone.

Warning: mysqli_close() expects parameter 1 to be mysqli, bool given in /var/www/html/index.php on line 102

**Comment by larry-athey** [comment]
The error says that the system settings record is missing from the database. Do any of the database tables exist? You can log into PhpMyAdmin (http://[your-pi-ip]/phpmyadmin) using the database credentials found at the top of subs.php and look at the database.

You can always run the install.sh script again and watch your screen for any errors.

**Comment by FireflySE** [comment]
Hi 

Thanks for the reply :)

I managed to set new password for root in safe mode so now I can access MariaDB at least.
I have databases as shown below. I will check subs.php if i can find it... 

MariaDB [(none)]> show databases;
+--------------------+
| Database           |
+--------------------+
| information_schema |
| mysql              |
| performance_schema |
| phpmyadmin         |
+--------------------+
4 rows in set (0,023 sec)

MariaDB [(none)]>

**Comment by larry-athey** [comment]
See line 75 of install.sh, that's where the database for the system is created. If you run the script again, you should be seeing an error if that step is failing. Obviously, it failed, or you would have a database named "rpismartstill" in your list.

**Comment by larry-athey** [comment]
I'm a bit baffled by what you said about setting a new root password. The part of the install script that secures the MySQL (mariadb) installation removes the root password. You can just use `sudo mysql` to get a command line.

Are you not using a stock unaltered Raspbian installation as the wiki suggests?

**Comment by FireflySE** [comment]
Yes I used a fresh install of latest 32bit debian legacy with desktop on my raspberry 3. I did not update before installation either. Also after installation bluetooth disappear so have to use VNC from my PC. Tried to connect to mysql but access denied the same as the browser message says. But something as you say must go wrong with installation because of the missing database I will make a new fresh install and pay more attention for errors.

**Comment by FireflySE** [comment]
I manage to see one error during installation "error unable to GET" but it disappears so fast and installation continues... Is there a log file some where? I checked again and the database is not installed. When installing MariaDB and phpmyadmin does it matter what I choose there or should it work either way?

Br

**Comment by larry-athey** [comment]
The log would be your terminal buffer, you just scroll the window backwards. You can also redirect the output of the script to a text file in order to create a log file by running `install.sh > install.log  2>&1`

**Comment by larry-athey** [comment]
Please pull the code tree again and re-run install.sh

```
You can delete this git clone after you are done, it is no longer needed.

pi@test-pi:~/rpi-smart-still/Undercarriage $ sudo mysql
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 62
Server version: 10.5.23-MariaDB-0+deb11u1 Raspbian 11

Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [(none)]> show databases;
+--------------------+
| Database           |
+--------------------+
| information_schema |
| mysql              |
| performance_schema |
| phpmyadmin         |
| rpismartstill      |
+--------------------+
5 rows in set (0.001 sec)

MariaDB [(none)]>
```

**Comment by FireflySE** [comment]
Thanks I will make another try tomorrow I get back to you with the result

**Comment by FireflySE** [comment]
pi@raspberrypi:~ $ sudo mysql
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 40
Server version: 10.5.23-MariaDB-0+deb11u1 Raspbian 11

Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [(none)]> show databases;
+--------------------+
| Database           |
+--------------------+
| information_schema |
| mysql              |
| performance_schema |
| phpmyadmin         |
+--------------------+
4 rows in set (0.002 sec)

MariaDB [(none)]>

**Comment by FireflySE** [comment]
This is what the log file shows

^[[H^[[2J^[[3JTHIS INSTALLER EXPECTS YOU TO BE USING A RAW UNMODIFIED OS INSTAL>

If you are using anything prior to a Raspberry Pi 4, you need to be running
a 32 bit version of Raspbian, even though there are 64 bit versions for it.
Unless you have 4+ GB of RAM, a 64 bit OS is completely useless. You surely
will have problems compiling the servo valve driver under a 64 bit Raspbian
on anything older than a Pi 4.

Press ENTER to continue the installation or CTRL+C to cancel...^[[?1049h^[[22;0>
^[[K
^[[K
^[[K
^[[K
^[[K
^[[K
^[[K
^[[K
^[[K
^[[K
^[[K^[[1;1H^[[37mPackage configuration^[[3;2H^[[30m^[[47m┌─────────────────────>

**Comment by larry-athey** [comment]
You didn't pull a fresh copy of the code. I can tell by the message at the beginning of the installation, it's missing a complete paragraph.

**Comment by FireflySE** [comment]
I deleted old clone and downloaded it again and now out of the blue the database appeared apparently the 4th time is the charm ;) and I can access via web browser so thank you so much.

**Comment by FireflySE** [comment]
Is there a config file for configure gpio pins etc? 
I have an electric heater so need to do some adjustment to the code and GUI.

**Comment by larry-athey** [comment]
This is all still pre-release. As you can see, there isn't even a first release version showing on the GitHub page. I'm slowly working on the PDF files in /Diagrams/ as I get free time. Until then, you have to refer to the source code. You will need to do regular code syncs until there is an official first release because things are updated here as I make changes on my end.

**Comment by FireflySE** [comment]
Then thank you for all the help and your hard work. Looking forward for the future of rpi smart still

Br
